音声合成画面
ynishikawa12/zundamon pull request #7
Opened 2024-06-30 14:31 UTC by ynishikawa12

## 解決したいこと
- GoでのVOICEVOXの音声合成結果をフロントで受け取り、blobオブジェクトを作成したい

## わからないこと
- Goでは音声合成結果をbase64エンコードしているが、エンコードする対象が正しいのか
- エンコードしたbase64文字列が正しいのか（試す方法がわからない）
- Buffer.from()が正しく使えているのか

## わかっている問題点
- console.logでblobオブジェクトを確認すると中身がないようにみえる（length:0など）
- base64エンコード or base64デコードに問題があると想定

2024-07-01 15:33 UTC, skanehira requested changes

2024-07-02 08:36 UTC, ynishikawa12 commented on frontend/src/components/Voice.tsx
> +  const [testVoiceUrl, setTestVoiceUrl] = useState("");
最終的にはvoices変数の配列に追加して、過去のものとあわせて表示するつもりです。
httpレスポンスにバイナリデータを与えるのをためすため、testとしています。
test変数はなくなる想定です。

2024-07-04 14:06 UTC, skanehira commented on frontend/src/components/Voice.tsx
> +type VoiceData = {
一瞬`Voice`との違いがわからなかったので、`VoiceResponse`のが良さそうね

2024-07-06 11:58 UTC, skanehira approved these changes

2024-07-13 10:41 UTC, merged